//! Types for the remote client protocol

use std::fmt;

use ap_noise::Psk;
use ap_proxy_protocol::IdentityFingerprint;
use serde::{Deserialize, Serialize};

/// A stable identifier for a PSK, derived from `hex(SHA256(psk)[0..8])`.
///
/// Used as a lookup key to match incoming handshakes to the correct pending
/// pairing. Today this maps to in-memory pending pairings; in the future it
/// could index persistent/reusable PSKs from a `PskStore`.
pub type PskId = String;

/// What kind of credential to look up.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum CredentialQuery {
    /// Look up by domain / URL.
    Domain(String),
    /// Look up by vault item ID.
    Id(String),
    /// Free-text search.
    Search(String),
}

impl CredentialQuery {
    /// Extract the inner search string from any query variant.
    pub fn search_string(&self) -> &str {
        match self {
            Self::Domain(d) => d.as_str(),
            Self::Id(id) => id.as_str(),
            Self::Search(s) => s.as_str(),
        }
    }
}

impl fmt::Display for CredentialQuery {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CredentialQuery::Domain(d) => write!(f, "domain: {d}"),
            CredentialQuery::Id(id) => write!(f, "id: {id}"),
            CredentialQuery::Search(s) => write!(f, "search: {s}"),
        }
    }
}

/// A parsed PSK token (`<64-hex-psk>_<64-hex-fingerprint>`, 129 chars).
///
/// Tokens are generated by [`UserClient::get_psk_token`] and parsed by
/// consumers that need to connect via PSK mode.
///
/// # Examples
///
/// ```
/// use ap_client::PskToken;
///
/// let token_str = format!("{}_{}", "ab".repeat(32), "cd".repeat(32));
/// let token = PskToken::parse(&token_str).unwrap();
/// assert_eq!(token.to_string(), token_str);
/// ```
#[derive(Debug, Clone)]
pub struct PskToken {
    psk: Psk,
    fingerprint: IdentityFingerprint,
}

impl PskToken {
    /// Create a new `PskToken` from its components.
    pub fn new(psk: Psk, fingerprint: IdentityFingerprint) -> Self {
        Self { psk, fingerprint }
    }

    /// Parse a PSK token string (`<64-hex-psk>_<64-hex-fingerprint>`).
    ///
    /// # Errors
    ///
    /// Returns [`ClientError::InvalidPairingCode`] if the format is invalid.
    pub fn parse(token: &str) -> Result<Self, crate::error::ClientError> {
        if token.len() != 129 {
            return Err(crate::error::ClientError::InvalidPairingCode(format!(
                "PSK token must be exactly 129 characters, got {}",
                token.len()
            )));
        }

        let (psk_hex, rest) = token.split_at(64);
        let (sep, fp_hex) = rest.split_at(1);
        if sep != "_" {
            return Err(crate::error::ClientError::InvalidPairingCode(
                "PSK token must have '_' separator at position 64".to_string(),
            ));
        }

        let psk = Psk::from_hex(psk_hex).map_err(|e| {
            crate::error::ClientError::InvalidPairingCode(format!("Invalid PSK: {e}"))
        })?;
        let fingerprint = IdentityFingerprint::from_hex(fp_hex).map_err(|e| {
            crate::error::ClientError::InvalidPairingCode(format!("Invalid fingerprint: {e}"))
        })?;

        Ok(Self { psk, fingerprint })
    }

    /// Cheap heuristic: returns `true` if the string looks like a PSK token.
    pub fn looks_like_psk_token(s: &str) -> bool {
        s.len() == 129 && s.as_bytes()[64] == b'_'
    }

    /// The pre-shared key.
    pub fn psk(&self) -> &Psk {
        &self.psk
    }

    /// The remote peer's identity fingerprint.
    pub fn fingerprint(&self) -> &IdentityFingerprint {
        &self.fingerprint
    }

    /// Consume the token into its parts.
    pub fn into_parts(self) -> (Psk, IdentityFingerprint) {
        (self.psk, self.fingerprint)
    }

    /// Convert into the corresponding [`ConnectionMode`].
    pub fn into_connection_mode(self) -> ConnectionMode {
        ConnectionMode::NewPsk {
            psk: self.psk,
            remote_fingerprint: self.fingerprint,
        }
    }
}

impl fmt::Display for PskToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}_{}", self.psk.to_hex(), self.fingerprint.to_hex())
    }
}

/// Connection mode for establishing a connection
#[derive(Debug, Clone)]
pub enum ConnectionMode {
    /// New connection requiring rendezvous code pairing
    New { rendezvous_code: String },
    /// New connection using PSK authentication
    NewPsk {
        psk: Psk,
        remote_fingerprint: IdentityFingerprint,
    },
    /// Existing connection using cached remote fingerprint
    Existing {
        remote_fingerprint: IdentityFingerprint,
    },
}

/// Credential data returned from a request
#[derive(Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CredentialData {
    /// Username for the credential
    #[serde(skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Password for the credential
    #[serde(skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    /// TOTP code if available
    #[serde(skip_serializing_if = "Option::is_none")]
    pub totp: Option<String>,
    /// URI associated with the credential
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    /// Additional notes
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Vault item ID
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential_id: Option<String>,
    /// Domain associated with this credential
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
}

impl std::fmt::Debug for CredentialData {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CredentialData")
            .field("domain", &self.domain)
            .field("username", &self.username)
            .field("password", &self.password.as_ref().map(|_| "[REDACTED]"))
            .field("totp", &self.totp.as_ref().map(|_| "[REDACTED]"))
            .field("notes", &self.notes.as_ref().map(|_| "[REDACTED]"))
            .field("credential_id", &self.credential_id)
            .finish()
    }
}

/// Internal protocol messages sent over WebSocket
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub(crate) enum ProtocolMessage {
    /// Noise handshake init (initiator -> responder)
    #[serde(rename = "handshake-init")]
    HandshakeInit {
        data: String,
        ciphersuite: String,
        /// PSK identifier — `Some(id)` for PSK mode, `None` for rendezvous mode.
        /// Backward-compatible: old clients omit this field (deserialized as `None`).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        psk_id: Option<PskId>,
    },
    /// Noise handshake response (responder -> initiator)
    #[serde(rename = "handshake-response")]
    HandshakeResponse { data: String, ciphersuite: String },
    /// Encrypted credential request
    CredentialRequest { encrypted: String },
    /// Encrypted credential response
    CredentialResponse { encrypted: String },
}

/// Internal credential request structure (encrypted in transit)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct CredentialRequestPayload {
    #[serde(rename = "type")]
    pub request_type: String,
    pub query: CredentialQuery,
    pub timestamp: u64,
    #[serde(rename = "requestId")]
    pub request_id: String,
}

/// Internal credential response structure (encrypted in transit)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct CredentialResponsePayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential: Option<CredentialData>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "requestId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn psk_token_roundtrip() {
        let psk = Psk::generate();
        let fp = IdentityFingerprint([0xcd; 32]);
        let token = PskToken::new(psk.clone(), fp);
        let s = token.to_string();
        assert_eq!(s.len(), 129);
        assert_eq!(s.as_bytes()[64], b'_');

        let parsed = PskToken::parse(&s).expect("should parse");
        assert_eq!(parsed.fingerprint(), &fp);
        assert_eq!(parsed.psk().to_hex(), psk.to_hex());
    }

    #[test]
    fn psk_token_parse_wrong_length() {
        assert!(PskToken::parse("too_short").is_err());
    }

    #[test]
    fn psk_token_looks_like() {
        let valid = format!("{}_{}", "ab".repeat(32), "cd".repeat(32));
        assert!(PskToken::looks_like_psk_token(&valid));
        assert!(!PskToken::looks_like_psk_token("ABC-DEF-GHI"));
    }

    #[test]
    fn psk_token_into_connection_mode() {
        let psk = Psk::generate();
        let fp = IdentityFingerprint([0x01; 32]);
        let token = PskToken::new(psk, fp);
        let mode = token.into_connection_mode();
        assert!(matches!(mode, ConnectionMode::NewPsk { .. }));
    }
}
